"""Google Gemini implementation of :class:`LLMBackend`.

Speaks Gemini's native REST API (``generateContent``) rather than its
OpenAI-compatibility shim, because two things the reply engine depends on
only work reliably on the native surface:

1. **Thought signatures.** Gemini 3 models attach an opaque
   ``thoughtSignature`` to every ``functionCall`` part and reject the next
   request (HTTP 4xx) when the signature is not echoed back. The backend
   carries each signature on its tool-call dict (``thought_signature``) so
   it survives the engine's message list and is restored on the next turn.
   Tool calls that never came from Gemini (carried over from an earlier
   reply, or built by hand) get the documented
   :data:`SKIP_THOUGHT_SIGNATURE` sentinel so validation still passes.
2. **Thinking control.** Gemini models think by default, which adds seconds
   to every call. Classification passes run with ``thinking=False``; the
   backend maps that to the cheapest setting the model accepts
   (``thinkingLevel: "minimal"`` → ``"low"`` for current models,
   ``thinkingBudget: 0`` → ``128`` for budget-era 1.x / 2.x models, and
   finally no control at all). A rejected setting is retried with the next
   candidate and the first one that works is remembered per model for the
   rest of the process, so the probe costs at most one extra round-trip.

Requests reuse one pooled HTTPS session for the process so consecutive
calls skip the TCP + TLS handshake to Google. The API key travels in the
``x-goog-api-key`` header (never the URL) and is never printed.

Response normalisation matches :class:`OpenAICompatibleBackend`: callers get
``{"message": {"role", "content", "tool_calls"}}`` with tool-call arguments
already decoded to a dict.
"""

from __future__ import annotations

import json
import re
import threading
import uuid
from typing import Any, Callable, Dict, List, Optional, Tuple

import requests
from requests.adapters import HTTPAdapter

from ..debug import debug_log
from ..utils.vector_store import MEMORY_EMBEDDING_DIMENSION
from .backend import LLMBackend, ToolsNotSupportedError
from .errors import is_timeout_error


DEFAULT_GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

# Documented sentinel for functionCall parts that were not generated by the
# API in this conversation (history carried over between replies). Gemini
# accepts it in place of a real signature.
SKIP_THOUGHT_SIGNATURE = "skip_thought_signature_validator"

# Ollama-only request knobs with no Gemini equivalent.
_DROPPED_OPTIONS = {"keep_alive", "num_ctx", "num_predict", "think"}

# Budget-era models (1.x / 2.x) control thinking with ``thinkingBudget``;
# everything newer (and the ``-latest`` aliases) uses ``thinkingLevel``.
_BUDGET_ERA = re.compile(r"^(?:models/)?gemini-[12](?:\.|-)", re.IGNORECASE)

# HTTP statuses that mean "this request shape is not accepted" and are worth
# retrying with a different thinking control.
_REJECTED_REQUEST = 400



class GeminiAuthError(requests.HTTPError):
    """The API key was rejected. Gemini reports an invalid key as HTTP 400
    with an ``API_KEY_*`` error reason, so this must be told apart from a
    rejected request shape before any shape-based fallback kicks in."""


def _error_reason(resp: requests.Response) -> str:
    """The structured ``ErrorInfo.reason`` of a Gemini error body, or ''."""
    try:
        details = (resp.json().get("error") or {}).get("details") or []
    except Exception:
        return ""
    for detail in details:
        if isinstance(detail, dict) and detail.get("reason"):
            return str(detail["reason"])
    return ""


def _is_auth_failure(resp: requests.Response) -> bool:
    return resp.status_code in (401, 403) or _error_reason(resp).startswith("API_KEY")


_session_lock = threading.Lock()
_session: Optional[requests.Session] = None

# (base_url, model, thinking) -> index into the thinking candidates that the
# model accepted. Module-level because the factory builds a fresh backend
# per call; the knowledge must outlive any single instance.
_quirks_lock = threading.Lock()
_thinking_choice: Dict[Tuple[str, str, bool], int] = {}


def reset_model_quirks() -> None:
    """Forget the learned per-model thinking settings (used by tests)."""
    with _quirks_lock:
        _thinking_choice.clear()


def _http() -> requests.Session:
    global _session
    with _session_lock:
        if _session is None:
            session = requests.Session()
            adapter = HTTPAdapter(pool_connections=4, pool_maxsize=16)
            session.mount("https://", adapter)
            session.mount("http://", adapter)
            _session = session
        return _session


def _thinking_candidates(model: str, thinking: bool) -> List[Optional[Dict[str, Any]]]:
    """Thinking controls to try, cheapest first. ``None`` means "send no
    thinking control" (the model default)."""
    if thinking:
        return [None]
    if _BUDGET_ERA.match(model.strip()):
        return [{"thinkingBudget": 0}, {"thinkingBudget": 128}, None]
    return [{"thinkingLevel": "minimal"}, {"thinkingLevel": "low"}, None]


def _model_path(model: str) -> str:
    name = model.strip()
    return name if name.startswith("models/") else f"models/{name}"


def _content_text(content: Any) -> str:
    """Flatten an OpenAI-style content value (string or parts list) to text."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts = []
        for part in content:
            if isinstance(part, dict) and isinstance(part.get("text"), str):
                texts.append(part["text"])
            elif isinstance(part, str):
                texts.append(part)
        return "\n".join(texts)
    return "" if content is None else str(content)


def _call_args(func: Dict[str, Any]) -> Dict[str, Any]:
    args = func.get("arguments")
    if isinstance(args, str):
        try:
            args = json.loads(args) if args.strip() else {}
        except (json.JSONDecodeError, ValueError):
            args = {}
    return args if isinstance(args, dict) else {}


def _translate_messages(
    messages: List[Dict[str, Any]],
) -> Tuple[List[str], List[Dict[str, Any]]]:
    """Convert engine messages to ``(system_texts, contents)``.

    - Leading system messages form the system instruction; later ones stay
      in conversation order as user-turn text.
    - Assistant tool calls become ``functionCall`` parts carrying their
      thought signature. Calls without a matching tool result are dropped
      (the engine executes one call per turn; Gemini rejects a call/response
      count mismatch).
    - Tool results become ``functionResponse`` parts on a user turn.
    - Consecutive turns with the same role are merged.
    """
    answered = {
        m.get("tool_call_id") for m in messages
        if m.get("role") == "tool" and m.get("tool_call_id")
    }
    call_names: Dict[str, str] = {}
    system_texts: List[str] = []
    contents: List[Dict[str, Any]] = []
    leading = True

    def add(role: str, parts: List[Dict[str, Any]]) -> None:
        if not parts:
            return
        if contents and contents[-1]["role"] == role:
            contents[-1]["parts"].extend(parts)
        else:
            contents.append({"role": role, "parts": parts})

    for msg in messages:
        role = msg.get("role")
        if role == "system":
            text = _content_text(msg.get("content"))
            if leading:
                if text:
                    system_texts.append(text)
            elif text:
                add("user", [{"text": text}])
            continue
        leading = False

        if role == "assistant":
            parts: List[Dict[str, Any]] = []
            text = _content_text(msg.get("content"))
            if text.strip():
                parts.append({"text": text})
            signed = False
            for tc in msg.get("tool_calls") or []:
                if not isinstance(tc, dict) or not isinstance(tc.get("function"), dict):
                    continue
                call_id = tc.get("id")
                if call_id not in answered:
                    continue
                func = tc["function"]
                name = str(func.get("name") or "")
                if call_id:
                    call_names[call_id] = name
                part: Dict[str, Any] = {"functionCall": {"name": name, "args": _call_args(func)}}
                signature = tc.get("thought_signature")
                if isinstance(signature, str) and signature:
                    part["thoughtSignature"] = signature
                    signed = True
                elif not signed:
                    part["thoughtSignature"] = SKIP_THOUGHT_SIGNATURE
                    signed = True
                parts.append(part)
            add("model", parts)
        elif role == "tool":
            call_id = msg.get("tool_call_id")
            name = call_names.get(call_id or "", "") or str(msg.get("name") or "tool")
            add("user", [{
                "functionResponse": {
                    "name": name,
                    "response": {"result": _content_text(msg.get("content"))},
                }
            }])
        else:
            text = _content_text(msg.get("content"))
            if text:
                add("user", [{"text": text}])

    return system_texts, contents


def _function_declarations(tools: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    decls: List[Dict[str, Any]] = []
    for tool in tools:
        func = tool.get("function") if isinstance(tool, dict) else None
        if not isinstance(func, dict) or not func.get("name"):
            continue
        decl: Dict[str, Any] = {"name": func["name"]}
        if func.get("description"):
            decl["description"] = func["description"]
        params = func.get("parameters")
        if isinstance(params, dict) and params:
            decl["parametersJsonSchema"] = params
        decls.append(decl)
    return decls


def _generation_config(options: Dict[str, Any]) -> Dict[str, Any]:
    """Map OpenAI/Ollama-style sampling options onto ``generationConfig``."""
    flat: Dict[str, Any] = {}
    for key, value in options.items():
        if key == "options" and isinstance(value, dict):
            flat.update(value)
        else:
            flat[key] = value
    gen: Dict[str, Any] = {}
    for key, value in flat.items():
        if key in _DROPPED_OPTIONS or value is None:
            continue
        if key == "temperature":
            gen["temperature"] = value
        elif key == "max_tokens":
            gen["maxOutputTokens"] = value
        elif key == "top_p":
            gen["topP"] = value
        elif key == "top_k":
            gen["topK"] = value
        elif key == "seed":
            gen["seed"] = value
        elif key == "stop":
            gen["stopSequences"] = [value] if isinstance(value, str) else list(value)
        elif key == "format":
            gen["responseMimeType"] = "application/json"
            if isinstance(value, dict):
                gen["responseJsonSchema"] = value
    return gen


def _normalise_response(data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Gemini response -> ``{"message": {...}}`` in the engine's shape.

    Thought parts are excluded from ``content``; each ``functionCall`` part
    becomes a tool call with an id and its thought signature attached."""
    candidates = data.get("candidates")
    if not isinstance(candidates, list) or not candidates:
        block = (data.get("promptFeedback") or {}).get("blockReason")
        debug_log(f"Gemini returned no candidates (block reason: {block or 'none'})", "llm")
        return None
    candidate = candidates[0] if isinstance(candidates[0], dict) else {}
    parts = (candidate.get("content") or {}).get("parts") or []
    texts: List[str] = []
    tool_calls: List[Dict[str, Any]] = []
    for part in parts:
        if not isinstance(part, dict):
            continue
        call = part.get("functionCall")
        if isinstance(call, dict):
            tc: Dict[str, Any] = {
                "id": call.get("id") or f"call_{uuid.uuid4().hex[:12]}",
                "type": "function",
                "function": {
                    "name": call.get("name", ""),
                    "arguments": call.get("args") if isinstance(call.get("args"), dict) else {},
                },
            }
            if part.get("thoughtSignature"):
                tc["thought_signature"] = part["thoughtSignature"]
            tool_calls.append(tc)
        elif isinstance(part.get("text"), str) and not part.get("thought"):
            texts.append(part["text"])
    message: Dict[str, Any] = {"role": "assistant", "content": "".join(texts)}
    if tool_calls:
        message["tool_calls"] = tool_calls
    out: Dict[str, Any] = {"message": message}
    if candidate.get("finishReason"):
        out["done_reason"] = candidate["finishReason"]
    return out


class GeminiBackend(LLMBackend):
    """:class:`LLMBackend` implementation for the Google Gemini API."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
        embedding_dimension: int = MEMORY_EMBEDDING_DIMENSION,
    ) -> None:
        self._base_url = (base_url or DEFAULT_GEMINI_BASE_URL).rstrip("/")
        self._api_key = api_key or None
        self._embedding_dimension = embedding_dimension

    @property
    def base_url(self) -> str:
        return self._base_url

    def _headers(self) -> Dict[str, str]:
        headers = {"Content-Type": "application/json"}
        if self._api_key:
            headers["x-goog-api-key"] = self._api_key
        return headers

    # ── core request with thinking negotiation ─────────────────────────

    def _generate(
        self,
        model: str,
        messages: List[Dict[str, Any]],
        *,
        options: Optional[Dict[str, Any]],
        tools: Optional[List[Dict[str, Any]]],
        thinking: bool,
        timeout_sec: float,
        stream: bool = False,
    ) -> requests.Response:
        """POST a generate request, walking the thinking candidates on
        rejection. Returns the successful (still open when streaming)
        response, or raises the last ``HTTPError``."""
        system_texts, contents = _translate_messages(messages)
        payload: Dict[str, Any] = {"contents": contents}
        if system_texts:
            payload["systemInstruction"] = {"parts": [{"text": "\n\n".join(system_texts)}]}
        decls = _function_declarations(tools or [])
        if decls:
            payload["tools"] = [{"functionDeclarations": decls}]
        base_gen = _generation_config(options or {})

        candidates = _thinking_candidates(model, thinking)
        key = (self._base_url, model, thinking)
        with _quirks_lock:
            start = min(_thinking_choice.get(key, 0), len(candidates) - 1)

        action = "streamGenerateContent" if stream else "generateContent"
        url = f"{self._base_url}/{_model_path(model)}:{action}"
        params = {"alt": "sse"} if stream else None

        last_error: Optional[requests.HTTPError] = None
        for index in range(start, len(candidates)):
            gen = dict(base_gen)
            if candidates[index] is not None:
                gen["thinkingConfig"] = candidates[index]
            body = dict(payload)
            if gen:
                body["generationConfig"] = gen
            resp = _http().post(
                url, json=body, headers=self._headers(), params=params,
                timeout=timeout_sec, stream=stream,
            )
            try:
                resp.raise_for_status()
            except requests.HTTPError as exc:
                auth_failed = _is_auth_failure(resp)
                resp.close()
                if auth_failed:
                    debug_log(f"Gemini rejected the API key (HTTP {resp.status_code})", "llm")
                    raise GeminiAuthError(response=resp) from exc
                last_error = exc
                if resp.status_code == _REJECTED_REQUEST and index + 1 < len(candidates):
                    debug_log(
                        f"Gemini rejected thinking control {candidates[index]} for {model}; trying the next one",
                        "llm",
                    )
                    continue
                raise
            if index != start:
                with _quirks_lock:
                    _thinking_choice[key] = index
                debug_log(f"Gemini thinking control for {model} settled on {candidates[index]}", "llm")
            return resp
        assert last_error is not None
        raise last_error

    # ── chat ───────────────────────────────────────────────────────────

    def direct(
        self,
        chat_model: str,
        system_prompt: str,
        user_content: str,
        timeout_sec: float = 10.0,
        thinking: bool = False,
        num_ctx: int = 4096,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> Optional[str]:
        # ``num_ctx`` has no equivalent: Gemini context windows are fixed
        # server-side. Accepted for signature parity with OllamaBackend.
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]
        options = {"temperature": temperature, "max_tokens": max_tokens}
        try:
            resp = self._generate(chat_model, messages, options=options, tools=None,
                                  thinking=thinking, timeout_sec=timeout_sec)
            with resp:
                data = resp.json()
            normalised = _normalise_response(data) if isinstance(data, dict) else None
            content = (normalised or {}).get("message", {}).get("content")
            if isinstance(content, str) and content.strip():
                return content
            debug_log("GeminiBackend.direct: empty content", "llm")
        except requests.exceptions.Timeout:
            debug_log(f"GeminiBackend.direct: timeout after {timeout_sec}s", "llm")
        except requests.HTTPError as e:
            status = e.response.status_code if e.response is not None else "?"
            debug_log(f"GeminiBackend.direct: HTTP {status}", "llm")
        except Exception as e:
            debug_log(f"GeminiBackend.direct: request failed ({type(e).__name__})", "llm")
        return None

    def streaming(
        self,
        chat_model: str,
        system_prompt: str,
        user_content: str,
        on_token: Optional[Callable[[str], None]] = None,
        timeout_sec: float = 30.0,
        thinking: bool = False,
    ) -> Optional[str]:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]
        try:
            resp = self._generate(chat_model, messages, options=None, tools=None,
                                  thinking=thinking, timeout_sec=timeout_sec, stream=True)
            full: List[str] = []
            with resp:
                for raw in resp.iter_lines():
                    if not raw:
                        continue
                    line = raw.decode("utf-8", errors="ignore") if isinstance(raw, bytes) else raw
                    if not line.startswith("data:"):
                        continue
                    try:
                        chunk = json.loads(line[len("data:"):].strip())
                    except json.JSONDecodeError:
                        continue
                    normalised = _normalise_response(chunk) if isinstance(chunk, dict) else None
                    text = (normalised or {}).get("message", {}).get("content") or ""
                    if text:
                        full.append(text)
                        if on_token:
                            on_token(text)
            result = "".join(full)
            return result if result.strip() else None
        except Exception as e:
            debug_log(f"GeminiBackend.streaming: failed ({type(e).__name__})", "llm")
            return None

    def chat(
        self,
        chat_model: str,
        messages: List[Dict[str, Any]],
        timeout_sec: float = 30.0,
        extra_options: Optional[Dict[str, Any]] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
        thinking: bool = False,
    ) -> Optional[Dict[str, Any]]:
        try:
            resp = self._generate(chat_model, messages, options=extra_options, tools=tools,
                                  thinking=thinking, timeout_sec=timeout_sec)
            with resp:
                data = resp.json()
            if isinstance(data, dict):
                return _normalise_response(data)
        except requests.exceptions.Timeout:
            print(f"  ⏱️ LLM request timed out (configured timeout: {timeout_sec:g}s)", flush=True)
            return None
        except requests.exceptions.ConnectionError as exc:
            if is_timeout_error(exc):
                debug_log("Gemini chat response read timed out (wrapped transport timeout)", "llm")
                print(f"  ⏱️ LLM request timed out (configured timeout: {timeout_sec:g}s)", flush=True)
                return None
            print("  ❌ LLM connection error", flush=True)
            raise
        except GeminiAuthError:
            print("  🔑 Gemini API key was rejected; check it in Settings → LLM Provider", flush=True)
            return None
        except requests.HTTPError as e:
            status = e.response.status_code if e.response is not None else None
            if status == _REJECTED_REQUEST and tools:
                raise ToolsNotSupportedError(
                    f"Model {chat_model!r} returned HTTP 400 — native tools API not supported"
                )
            if status == 429:
                print("  ⏳ Gemini rate limit reached (HTTP 429)", flush=True)
            else:
                print(f"  ❌ LLM HTTP error (status {status or '?'})", flush=True)
            return None
        except Exception as e:
            print(f"  ❌ LLM error ({type(e).__name__})", flush=True)
            return None
        return None

    # ── embeddings & discovery ────────────────────────────────────────

    def embed(
        self,
        text: str,
        model: str,
        timeout_sec: float = 15.0,
    ) -> Optional[List[float]]:
        body = {
            "content": {"parts": [{"text": text}]},
            "outputDimensionality": self._embedding_dimension,
        }
        try:
            with _http().post(
                f"{self._base_url}/{_model_path(model)}:embedContent",
                json=body, headers=self._headers(), timeout=timeout_sec,
            ) as resp:
                resp.raise_for_status()
                data = resp.json()
            values = ((data or {}).get("embedding") or {}).get("values")
            if isinstance(values, list) and values:
                return [float(x) for x in values]
        except Exception as e:
            debug_log(f"GeminiBackend.embed: failed ({type(e).__name__})", "llm")
        return None

    def list_models(self, timeout_sec: float = 5.0) -> List[str]:
        names: List[str] = []
        page_token: Optional[str] = None
        try:
            for _ in range(20):  # bounded pagination
                params: Dict[str, Any] = {"pageSize": 1000}
                if page_token:
                    params["pageToken"] = page_token
                with _http().get(
                    f"{self._base_url}/models", headers=self._headers(),
                    params=params, timeout=timeout_sec,
                ) as resp:
                    resp.raise_for_status()
                    data = resp.json()
                for m in data.get("models", []) if isinstance(data, dict) else []:
                    if not isinstance(m, dict):
                        continue
                    methods = m.get("supportedGenerationMethods") or []
                    name = str(m.get("name") or "")
                    if "generateContent" in methods and name:
                        names.append(name[len("models/"):] if name.startswith("models/") else name)
                page_token = data.get("nextPageToken") if isinstance(data, dict) else None
                if not page_token:
                    break
        except Exception as e:
            debug_log(f"GeminiBackend.list_models: failed ({type(e).__name__})", "llm")
            return []
        return names

    def warm_up(
        self,
        model: str,
        timeout_sec: float = 60.0,
        keep_alive: str = "30m",
    ) -> bool:
        """Open the pooled HTTPS connection and confirm the key can reach
        ``model`` with a metadata lookup (``GET models/{model}``). Gemini
        models are always resident, so no generation is spent; the benefit
        is that the first real request skips the TCP + TLS handshake and a
        bad key or model name is reported before the user speaks.
        ``keep_alive`` is accepted for signature parity and ignored."""
        if not model:
            return False
        try:
            with _http().get(
                f"{self._base_url}/{_model_path(model)}",
                headers=self._headers(), timeout=min(timeout_sec, 15.0),
            ) as resp:
                ok = resp.ok
            debug_log(f"Gemini warm-up for {model}: {'ok' if ok else 'failed'}", "llm")
            return ok
        except Exception as e:
            debug_log(f"Gemini warm-up for {model} failed ({type(e).__name__})", "llm")
            return False
